### ISSUE TITLE
可视化数据界面打开时报错

### ISSUE THREAD

**Issue by cirno99** [hyfand/wechat_spider#1]
在浏览器地址栏输入：
**http://localhost:8104/**

报错如下：
**ENOENT: no such file or directory, stat '/home/wuzixian/wechat_spider/client/build/index.html'**

终端：

**GET** /?mainData=true&perPage=20&q=%E5%AD%A9%E5%AD%90%E5%92%B3%E5%97%BD **500** 7.592 ms - 117
**GET** /favicon.ico **500** 1.318 ms - 117

**Comment by hyfand** [comment]
你的路径错了吧估计， 确信没问题的 ，我一直在正常运行
